// <auto-generated />
namespace Nigon.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Activation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Activation));
        
        string IMigrationMetadata.Id
        {
            get { return "201703270908082_Activation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
